baseurl: /
languageCode: en-us
title: Bo Shao
theme: "hugo-ivy"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: ↩

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Publications"
      url: "/publications/"
      weight: 3
    - name: "Honors"
      url: "/honors/"
      weight: 4
    - name: "Personal"
      url: "/personal/"
      weight: 5

params:
  description: "Put head down and fight! Never, ever, ever give up!"
  footer: "&copy; [Bo Shao](https://boshao.netlify.app) 2024 | [LinkedIn](https://www.linkedin.com/in/boshao321/) | [ResearchGate](https://www.researchgate.net/profile/Bo-Shao-15) | [ORCID](https://orcid.org/0000-0002-3360-8886)"
  highlightjsCDN: "//cdn.bootcss.com"
  highlightjsLang: ["r", "yaml", "tex", "latex"]
  highlightjsTheme: "github"
  highlightjsVersion: "11.7.0"
  disqusURL: "https://boshao.netlify.app"
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"

blackfriday:
    extensionsmask: ["noIntraEmphasis"]
    fractions: false

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
